<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require __DIR__.'/TestDoubles.php';
use Nerozon\Questionnaire\{QuestionnaireDefinition,SubmitQuestionnaire,InvalidQuestionnaireSubmission};use Nerozon\Http\HttpConnector;use Nerozon\Tests\MemoryRepository;
$tests=[];$test=function(string $n,callable $f)use(&$tests){$tests[$n]=$f;};$assert=function(bool $v,string $m='assertion failed'){if(!$v)throw new RuntimeException($m);};
$test('empty submission',function()use($assert){$r=new MemoryRepository;$u=new SubmitQuestionnaire($r);$assert($u->execute(['questionnaire_id'=>'S092026','questionnaire_version'=>'20260830','answers'=>[]])['accepted']===true);$assert(count($r->saved)===1&&$r->saved[0]->answers===[]);});
$test('partial canonical mapping',function()use($assert){$a=QuestionnaireDefinition::normalizeAnswers([['question_id'=>'S092026Q02','type'=>'multi_choice','value'=>['S092026Q02A01','S092026Q02A08']],['question_id'=>'S092026Q10','type'=>'short_text','value'=>'  Hallo  ']]);$assert(count($a)===2&&$a[1]->value==='Hallo');});
$test('invalid choice rejected',function()use($assert){try{QuestionnaireDefinition::normalizeAnswers([['question_id'=>'S092026Q01','type'=>'single_choice','value'=>'S092026Q01A05']]);throw new RuntimeException('not rejected');}catch(InvalidQuestionnaireSubmission){$assert(true);}});
$test('duplicate question rejected',function()use($assert){try{QuestionnaireDefinition::normalizeAnswers([['question_id'=>'S092026Q01','type'=>'single_choice','value'=>'S092026Q01A01'],['question_id'=>'S092026Q01','type'=>'single_choice','value'=>'S092026Q01A02']]);throw new RuntimeException('not rejected');}catch(InvalidQuestionnaireSubmission){$assert(true);}});
$test('http maps valid request',function()use($assert){$h=new HttpConnector(new SubmitQuestionnaire(new MemoryRepository));[$s,,$b]=$h->dispatch('POST','/v1/questionnaire/submissions','application/json',json_encode(['questionnaire_id'=>'S092026','questionnaire_version'=>'20260830','answers'=>[]]));$assert($s===201&&$b===['accepted'=>true]);});
$test('http rejects invalid json and method',function()use($assert){$h=new HttpConnector(new SubmitQuestionnaire(new MemoryRepository));$assert($h->dispatch('POST','/v1/questionnaire/submissions','application/json','{')[0]===400);$assert($h->dispatch('GET','/v1/questionnaire/submissions','application/json','{}')[0]===405);});
$failed=0;foreach($tests as $n=>$f){try{$f();echo "PASS $n\n";}catch(Throwable $e){$failed++;echo "FAIL $n: {$e->getMessage()}\n";}}exit($failed?1:0);
